// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK9DnlEaxFgu5E7_VGtm4J1Bjt1moHvMI',
    appId: '1:424268954678:web:a80457b840447524e1ac97',
    messagingSenderId: '424268954678',
    projectId: 't-u-mex-x693t8',
    authDomain: 't-u-mex-x693t8.firebaseapp.com',
    storageBucket: 't-u-mex-x693t8.appspot.com',
    measurementId: 'G-SNGGMXS8NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg21yxGKR99swrSO0PzbV9qwcv6Cf0gVQ',
    appId: '1:424268954678:android:1744b9eb386457fce1ac97',
    messagingSenderId: '424268954678',
    projectId: 't-u-mex-x693t8',
    storageBucket: 't-u-mex-x693t8.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeaaLgtfuGc-tIoSds3kzIvN4yCcZ-80A',
    appId: '1:424268954678:ios:6b7532cc84dac46be1ac97',
    messagingSenderId: '424268954678',
    projectId: 't-u-mex-x693t8',
    storageBucket: 't-u-mex-x693t8.appspot.com',
    iosBundleId: 'com.example.tumexUsersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlsMrKS6wge91NeNIaaC3xwLiOkRE39Po',
    appId: '1:424268954678:web:9a6a89758766d6f0e1ac97',
    messagingSenderId: '424268954678',
    projectId: 't-u-mex-x693t8',
    authDomain: 't-u-mex-x693t8.firebaseapp.com',
    storageBucket: 't-u-mex-x693t8.appspot.com',
    measurementId: 'G-260GF0TPF0',
  );
}
